
CREATE TABLE public.trail_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  category text NOT NULL CHECK (category IN ('Trail Guide','Trek Journal','Tips & Advice','Event Recap')),
  description text NOT NULL,
  pdf_url text,
  pdf_storage_path text,
  instagram_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT trail_log_source_check CHECK (
    (pdf_url IS NOT NULL AND instagram_url IS NULL)
    OR (pdf_url IS NULL AND instagram_url IS NOT NULL)
  )
);

GRANT SELECT ON public.trail_log TO anon, authenticated;
GRANT ALL ON public.trail_log TO service_role;

ALTER TABLE public.trail_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view trail log posts"
  ON public.trail_log FOR SELECT
  TO anon, authenticated
  USING (true);

-- Storage: allow service role only (admin edge function). Signed URLs generated by service role are usable by anyone with the link.
CREATE POLICY "Service role manages trail-log-pdfs"
  ON storage.objects FOR ALL
  TO service_role
  USING (bucket_id = 'trail-log-pdfs')
  WITH CHECK (bucket_id = 'trail-log-pdfs');
